### ISSUE TITLE
angular-flux with ngReact?

### ISSUE THREAD

**Issue by timh5** [brentvatne/angular-flux#1]
sorry if this is not the right protocol to start a discussion as an issue....

I built a decent sized angular app last year and am noticing performance issues now. (The UI has a lot goign on... maps, ng-repeats, lot of lists...etc...)  I'm Looking into ReactJS now when I stumbled upon this project. 

I understand that Flux is more of the data architecture side, and React is more of the rendering speed part.... so I'm curious as to your experience with both as far as performance goes. Or... what is the purpose of your project -- to simplify complex data archicture? ... or is this just playing around with an idea more than a serious implimentation?

**Comment by brentvatne** [comment]
Hi @timh5 

This is more just playing around with the idea, but there's no reason why you could not use it - it's the flux dispatcher.js and es6 eventemitter.js wrapped by Angular with some additional helper functions to make it easier to use. The purpose of the project is to get the one-way data flow model of Flux into Angular, rather than using two way bindings all over the place.

React is all about building are rendered using a virtual DOM / diffing and minimal updates algorithm, which is often more performant than Angular's approach. Usually the performance issues in Angular apps are related to having too many bindings - this is easy to do when you have a list of, say 100 items, and each item in the list has 10 bindings. See [this presentation](https://docs.google.com/presentation/d/15XgHRI8Ng2MXKZqglzP3PugWFZmIDKOnlAXDGZW2Djg/edit#slide=id.g2a03b8fde_024). You can look at replacing those lists with React components using [ngReact](https://github.com/davidchang/ngReact) or using some of the techniques described in that presentation.

Hope that helps,
Brent
